timeout = 60000
baseURL = '/'
languageCode = 'en-us'
title = 'FivexL. Cloud Engineering Specialists'

# this is just a place holder theme. please remove it later
theme = "example"

enableRobotsTXT = true

[pagination]
pagerSize = 6

# Main navigation
[menu]
[[menu.main]]
  identifier = 'products'
  name = 'Products'
  url = '#'
  weight = 3
[[menu.main]]
  identifier = 'rightstart'
  url = '/rightstart'
  name = 'RightStart'
  parent = 'products'
  weight = 1
[[menu.main]]
  identifier = 'ecs-blueprint'
  url = '/ecs-blueprint'
  name = 'ECS Blueprint'
  parent = 'products'
  weight = 2
[[menu.main]]
  identifier = 'retainer'
  url = '/retainer'
  name = 'Retainer Plans'
  parent = 'products'
  weight = 3
[[menu.main]]
  identifier = 'infra-clinic'
  url = '/infra_clinic'
  name = 'Infra Clinic for Startups'
  parent = 'products'
  weight = 4
[[menu.main]]
  url = '/contact'
  name = 'Contact'
  weight = 40
  [menu.main.params]
    class = "hdr-NavigationItem_Contact"
# Footer social links
[[menu.footer_external]]
  url = 'https://www.linkedin.com/company/5xl/'
  name = 'Linkedin'
  weight = 10
  [menu.footer_external.params]
    icon = 'linkedin'
[[menu.footer_external]]
  url = 'https://github.com/fivexl'
  name = 'Github'
  weight = 20
  [menu.footer_external.params]
    icon = 'github'
[[menu.footer_external]]
  url = 'https://www.youtube.com/@fivexl'
  name = 'YouTube'
  weight = 30
  [menu.footer_external.params]
    icon = 'youtube'

disableKinds = ['category'] # Categories disabled initially

[params]
  relatedBlogsLength = 3
  description = "FivexL blog and case studies - Expert AWS insights, DevOps best practices, cloud engineering guidance, and real-world success stories"
  [params.author]
    name = "FivexL"
    email = "info@fivexl.io"

[imaging]
  quality = 80

[outputs]
  home = ['HTML', 'RSS']
  section = ['HTML', 'JSON', 'RSS']

[markup]
  defaultMarkdownHandler = "goldmark"
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
